@startuml
class com.cnpm.controllers.ThemNhanKhauController {
- TextField bi_danh
- TextField dan_toc
- TextField dia_chi_hien_nay
- TextField gioi_tinh
- TextField ho_ten
- DatePicker ngay_sinh
- TextField nghe_nghiep
- TextField nguyen_quan
- TextField noi_lam_viec
- TextField noi_sinh
- TextField noi_thuong_tru
- TextField quoc_tich
- TextField so_dien_thoai
- TextField tien_an
- TextField ton_giao
- TextField trinh_do_chuyen_mon
- TextField trinh_do_ngoai_ngu
~ String query
~ Connection connection
~ PreparedStatement preparedStatement
~ Stage stage
+ void huy(ActionEvent)
+ void xacNhan(ActionEvent)
- void getQuery()
+ void initialize(URL,ResourceBundle)
}
class com.cnpm.controllers.PhatQuaController1 {
- TextField thong_tin_tim_kiem
- ChoiceBox loc
- ChoiceBox<String> optionChoiceBox
- Button findBtn
- TextField keywordTextField
- TableView<PhatQuaTableModel> table
- TableColumn<PhatQuaTableModel,String> hoTenCol
- TableColumn<PhatQuaTableModel,String> tenQuaCol
- TableColumn<PhatQuaTableModel,String> tuoiCol
- TableColumn<PhatQuaTableModel,String> tenDotPhatCol
- TableColumn<PhatQuaTableModel,String> giaTriCol
- TableColumn<PhatQuaTableModel,String> daDuyetCol
~ PhatQuaTableModel data
~ ObservableList<PhatQuaTableModel> listView
- TableColumn<com.cnpm.controllers.PhatQuaController,String> xoaCol
- List<PhatQuaTableModel> performFiltering(String,String)
+ void initialize(URL,ResourceBundle)
+ void duyet(ActionEvent)
+ void huyDuyet(ActionEvent)
}
class com.cnpm.controllers.XoaMinhChung {
- Button btn_cancel_them
- Button btn_confirm_them
- TextField note
- TextField dien_id_minh_chung
~ String query
~ Connection connection
~ ResultSet resultSet
~ MinhChung minhchung
~ PreparedStatement preparedStatement
+ void huy(ActionEvent)
+ void xacNhan(ActionEvent)
- void getQuery()
+ void initialize(URL,ResourceBundle)
}
class com.cnpm.controllers.ThemThuongController {
- Button btn_cancel_them
- Button btn_confirm_them
- TextField note
- TextField them_id_phat_thuong
- TextField them_id_dot_phat
- TextField them_id_qua
- TextField them_id_minh_chung
~ String query
~ Connection connection
~ ResultSet resultSet
~ PhatThuong pt
~ PreparedStatement preparedStatement
+ void huy(ActionEvent)
+ void xacNhan(ActionEvent)
- void getQuery()
+ void initialize(URL,ResourceBundle)
}
class com.cnpm.controllers.DangNhapController {
- TextField username
- PasswordField password
- Label alert
+ void dangNhap(ActionEvent)
+ void initialize(URL,ResourceBundle)
}
class com.cnpm.controllers.ThongKeNhanKhauController {
- TextField fromAgeTxt
- TextField toAgeTxt
- TextField nhanKhauThongKeTxt
- DatePicker fromYearTxt
- DatePicker toYearTxt
- Button cancleBtn
- Label errorLab
- TableView<NhanKhauTableModel> nhanKhauTable
- TableColumn maNhanKhauCol
- TableColumn tuoiCol
- TableColumn gioiTinhCol
- TableColumn maHoKhauCol
- TableColumn hoTenCol
- TableColumn ngaySinhCol
- CheckBox maleCheckBox
- CheckBox femaleCheckBox
+ void refreshTable()
+ void initialize(URL,ResourceBundle)
+ void cancle(ActionEvent)
}
class com.cnpm.controllers.DangKyTamTruController {
~ String query
~ Connection connection
~ PreparedStatement preparedStatement
~ Stage stage
- TextField co_quan_khai_bao
- TextArea ly_do
- TextField ma_nhan_khau
- DatePicker ngay_bat_dau
- DatePicker ngay_ket_thuc
- TextField noi_tam_tru
~ void huy(ActionEvent)
~ void xacNhan(ActionEvent)
+ void initialize(URL,ResourceBundle)
- void getQuery()
}
class com.cnpm.controllers.HoKhauController {
- TextField thong_tin_tim_kiem
- ChoiceBox loc
- Button them_ho_khau
- Button chuyen_ho_khau
- Button tach_ho_khau
- Button doi_chu_ho
- Button lich_su_thay_doi_ho_khau
- ChoiceBox<String> optionChoiceBox
- Button findBtn
- Label errorLab
- TextField keywordTextField
- TableView<HoKhauTableModel> table
- TableColumn<HoKhauTableModel,String> maHoKhauCol
- TableColumn<HoKhauTableModel,String> hoTenChuHoCol
- TableColumn<HoKhauTableModel,String> diaChiCol
- TableColumn<HoKhauTableModel,String> soThanhVienCol
- TableColumn<HoKhauTableModel,String> xoaCol
~ ObservableList<HoKhauTableModel> listView
+ void refreshTable()
+ void initialize(URL,ResourceBundle)
+ void themHoKhau(ActionEvent)
+ void doiChuHo(ActionEvent)
+ void tachHoKhau(ActionEvent)
+ void chuyenHoKhau(ActionEvent)
+ void lichSuThayDoi(ActionEvent)
+ void xoaHoKhau(ActionEvent)
}
class com.cnpm.controllers.NhanKhauController {
~ String query
~ Connection connection
~ PreparedStatement preparedStatement1
~ ResultSet resultSet
~ ObservableList<NhanKhau> NhanKhauList
~ SimpleDateFormat formatter
- ChoiceBox<String> optionChoiceBox
- TextField keywordTextField
- TableColumn<NhanKhau,String> diaChiHienNayCol
- TableColumn<NhanKhau,String> hoTenCol
- TableColumn<NhanKhau,String> maNhanKhauCol
- TableColumn<NhanKhau,String> ngaySinhCol
- TableColumn<NhanKhau,Integer> idCol
- TableColumn<NhanKhau,CheckBox> xoaCol
- TableView<NhanKhau> table
+ void refresh()
+ void themNhanKhau(ActionEvent)
+ void initialize(URL,ResourceBundle)
- void load()
- void restartScene(Scene)
+ void dangKyTamVang(ActionEvent)
+ void dangKyTamTru(ActionEvent)
+ void xoaNhanKhau(ActionEvent)
+ void thayDoiNhanKhau(ActionEvent)
}
class com.cnpm.controllers.PhatThuongController1 {
- TextField thong_tin_tim_kiem
- ChoiceBox loc
- ChoiceBox<String> optionChoiceBox
- Button findBtn
- TextField keywordTextField
- TableView<PhatThuongTableModel> table
- TableColumn<PhatThuongTableModel,String> hoTenCol
- TableColumn<PhatThuongTableModel,String> tenQuaCol
- TableColumn<PhatThuongTableModel,String> thanhTichHocTapCol
- TableColumn<PhatThuongTableModel,String> tenDotPhatCol
- TableColumn<PhatThuongTableModel,String> giaTriCol
- TableColumn<PhatThuongTableModel,String> daDuyetCol
~ PhatThuongTableModel data
~ ObservableList<PhatThuongTableModel> listView
- TableColumn<PhatThuongTableModel,String> xoaCol
- List<PhatThuongTableModel> performFiltering(String,String)
+ void initialize(URL,ResourceBundle)
+ void duyet(ActionEvent)
+ void huyDuyet(ActionEvent)
}
class com.cnpm.controllers.PhatThuongController {
- Button them_thuong
- TextField thong_tin_tim_kiem
- ChoiceBox loc
- ChoiceBox<String> optionChoiceBox
- Button findBtn
- TextField keywordTextField
- TableView<PhatThuongTableModel> table
- TableColumn<PhatThuongTableModel,String> hoTenCol
- TableColumn<PhatThuongTableModel,String> tenQuaCol
- TableColumn<PhatThuongTableModel,String> thanhTichHocTapCol
- TableColumn<PhatThuongTableModel,String> tenDotPhatCol
- TableColumn<PhatThuongTableModel,String> giaTriCol
- TableColumn<PhatThuongTableModel,String> daDuyetCol
~ PhatThuongTableModel data
~ ObservableList<PhatThuongTableModel> listView
- TableColumn<PhatThuongTableModel,String> xoaCol
- List<PhatThuongTableModel> performFiltering(String,String)
+ void initialize(URL,ResourceBundle)
+ void xoaThuong(ActionEvent)
+ void themThuong(ActionEvent)
}
class com.cnpm.controllers.ThayDoiNhanKhauController {
- TextField bi_danh
- TextField dan_toc
- TextField dia_chi_hien_nay
- TextField gioi_tinh
- TextField ho_ten
- TextField input_ho_ten
- DatePicker input_ngay_sinh
- DatePicker ngay_sinh
- TextField nghe_nghiep
- TextField nguyen_quan
- TextField noi_lam_viec
- TextField noi_sinh
- TextField noi_thuong_tru
- TextField quoc_tich
- TextField so_dien_thoai
- TextField tien_an
- TextField ton_giao
- TextField trinh_do_chuyen_mon
- TextField trinh_do_ngoai_ngu
- ChoiceBox<String> da_xoa
~ String query_find
~ Connection connection
~ Statement statement
~ PreparedStatement preparedStatement
~ ResultSet resultSet
~ Stage stage
~ int id
+ void capNhat(ActionEvent)
+ void huy(ActionEvent)
+ void timKiem(ActionEvent)
+ void initialize(URL,ResourceBundle)
}
class com.cnpm.controllers.XoaThuongController {
- Button btn_cancel_them
- Button btn_confirm_them
- TextField note
- TextField them_id_phat_thuong
~ String query
~ Connection connection
~ ResultSet resultSet
~ PhatThuong pt
~ PreparedStatement preparedStatement
+ void huy(ActionEvent)
+ void xacNhan(ActionEvent)
- void getQuery()
+ void initialize(URL,ResourceBundle)
}
class com.cnpm.controllers.ChonNhanKhauController {
- TableView nhanKhauTable
- TableColumn maNhanKhauCol
- TableColumn hoTenCol
- TableColumn quanHeVoiChuHoCol
- Button addNhanKhauBtn
- SharedDataModel sharedDataModel
+ void initialize(URL,ResourceBundle)
+ void setSharedDataModel(SharedDataModel)
}
class com.cnpm.controllers.MinhChungcontroller {
- Button them_minh_chung
- TextField thong_tin_tim_kiem
- ChoiceBox loc
- ChoiceBox<String> optionChoiceBox
- Button findBtn
- TextField keywordTextField
- TableView<MinhChungTableModel> table
- TableColumn<MinhChungTableModel,String> hoTenCol
- TableColumn<MinhChungTableModel,String> thanhTichHocTapCol
- TableColumn<MinhChungTableModel,String> truongCol
- TableColumn<MinhChungTableModel,String> lopCol
- TableColumn<MinhChungTableModel,String> ngayKhaiBaoCol
~ MinhChungTableModel data
~ ObservableList<MinhChungTableModel> listView
- TableColumn<MinhChungTableModel,String> xoaCol
- List<MinhChungTableModel> performFiltering(String,String)
+ void refresh()
+ void initialize(URL,ResourceBundle)
+ void xoaMinhChung(ActionEvent)
+ void themMinhChung(ActionEvent)
}
class com.cnpm.controllers.DoiChuHoController {
- Button cancleBtn
- TextField maHoKhauTxt
- ChoiceBox<String> quanHeVoiChuHoChoiceBox
- TextField maChuHoOldTxt
- TextField hoTenOldTxt
- TextField maChuHoNewTxt
- TextField hoTenMoiTxt
- TableView<HoKhauTableModel> hoKhauTable
- TableView<NhanKhauTableModel> nhanKhauTable
- TableColumn<HoKhauTableModel,String> maHoKhauCol
- TableColumn<HoKhauTableModel,String> hoTenChuHoCol
- TableColumn<HoKhauTableModel,String> diaChiCol
- Label errorLab
+ TextField maHoKhauTim
- ChoiceBox<String> optionChoiceBox
- TableColumn<NhanKhauTableModel,String> maNhanKhauCol
- TableColumn<NhanKhauTableModel,String> hoTenNhanKhauCol
- TableColumn<NhanKhauTableModel,String> quanHeVoiChuHoCol
- ChoiceBox<String> choiceBox
+ void submit(ActionEvent)
- void restartScene(Scene)
+ void cancle(ActionEvent)
+ void initialize(URL,ResourceBundle)
}
class com.cnpm.controllers.ThemQuaController {
- Button btn_cancel_them
- Button btn_confirm_them
- TextField note
- TextField them_id_phat_qua
- TextField them_id_dot_phat_qua
- TextField them_ma_nhan_khau
- TextField them_id_qua
~ String query
~ Connection connection
~ ResultSet resultSet
~ PhatQua phatqua
~ PreparedStatement preparedStatement
+ void huy(ActionEvent)
+ void xacNhan(ActionEvent)
- void getQuery()
+ void initialize(URL,ResourceBundle)
}
class com.cnpm.controllers.MacDinhController {
~ Connection connection
~ ResultSet resultSet1
~ String query1
- Label hoKhauLab
- Label nhanKhauLab
- Label nhanKhauTamTruLab
- Label nhanKhauTamVangLab
~ void logout(ActionEvent)
+ void initialize(URL,ResourceBundle)
- void getQuery()
}
class com.cnpm.controllers.PhatQuaController {
- Button them_qua
- TextField thong_tin_tim_kiem
- ChoiceBox loc
- ChoiceBox<String> optionChoiceBox
- Button findBtn
- TextField keywordTextField
- TableView<PhatQuaTableModel> table
- TableColumn<PhatQuaTableModel,String> hoTenCol
- TableColumn<PhatQuaTableModel,String> tenQuaCol
- TableColumn<PhatQuaTableModel,String> tuoiCol
- TableColumn<PhatQuaTableModel,String> tenDotPhatCol
- TableColumn<PhatQuaTableModel,String> giaTriCol
- TableColumn<PhatQuaTableModel,String> daDuyetCol
~ PhatQuaTableModel data
~ ObservableList<PhatQuaTableModel> listView
- TableColumn<PhatQuaController,String> xoaCol
- List<PhatQuaTableModel> performFiltering(String,String)
+ void initialize(URL,ResourceBundle)
+ void xoaQua(ActionEvent)
+ void themQua(ActionEvent)
}
class com.cnpm.controllers.DangKyTamVangController {
~ String query
~ Connection connection
~ PreparedStatement preparedStatement
~ Stage stage
- TextField co_quan_khai_bao
- TextArea ly_do
- TextField ma_nhan_khau
- DatePicker ngay_bat_dau
- DatePicker ngay_ket_thuc
~ void huy(ActionEvent)
~ void xacNhan(ActionEvent)
+ void initialize(URL,ResourceBundle)
- void getQuery()
}
class com.cnpm.controllers.XinCapGiayController {
- TextField cmndTxt
- TextField maCapGiayTxt
- TextField diaChiTxt
- TextArea lyDoTxt
- Button cancleBtn
- Button submitBtn
- DatePicker fromDatePicker
- DatePicker toDatePicker
+ void initialize(URL,ResourceBundle)
}
class com.cnpm.controllers.LichSuThayDoiController {
- TableView thayDoiTable
- TableColumn maHoKhauCol
- TableColumn tenChuHoCol
- TableColumn themNhanKhauCol
- TableColumn xoaNhanKhauCol
- TableColumn ngayThayDoiCol
- TableColumn ghiChuCol
- TextField findTxt
- TextField maHoKhauTxt
- TextField tenChuHoTxt
- TextField nhanKhauTxt
- TextField ghiChuTxt
- Button cancleBtn
- ChoiceBox<String> optionChoiceBox
+ void initialize(URL,ResourceBundle)
+ void cancle(ActionEvent)
}
class com.cnpm.controllers.ThemMinhChungController {
- Button btn_cancel_them
- Button btn_confirm_them
- TextField note
- TextField them_id_minh_chung
- TextField them_ma_nhan_khau
- TextField them_truong
- TextField them_lop
- TextField them_thanh_tich_hoc_tap
- DatePicker them_ngay_khai_bao
~ String query
~ Connection connection
~ ResultSet resultSet
~ MinhChung minhchung
~ PreparedStatement preparedStatement
~ SimpleDateFormat formatter
+ void huy(ActionEvent)
+ void xacNhan(ActionEvent)
- void getQuery()
+ void initialize(URL,ResourceBundle)
}
class com.cnpm.controllers.ThemHoKhauController {
- TextField maHoKhauTxt
- TextField maChuHoTxt
- TextField maKhuVucTxt
- TextField diaChiTxt
- TextField hoTenChuHoTxt
- TextField ngaySinhChuHoTxt
- TextField cccdChuHoTxt
- Button pickChuHoBtn
- Button cancleBtn
- Button submitBtn
- Button pickMemberBtn
- Label errorLab
- TableView<NhanKhauTableModel> nhanKhauTable
- TableColumn<NhanKhauTableModel,String> maNhanKhauCol
- TableColumn<NhanKhauTableModel,Date> hoTenCol
- TableColumn<NhanKhauTableModel,String> quanHeVoiChuHoCol
- SharedDataModel sharedDataModel
- ChoiceBox<String> choiceBox
- Button deleteNhanKhauBtn
- Button deleteAllNhanKhauBtn
- boolean containsNhanKhau(ObservableList<NhanKhauTableModel>,String)
- void removeNhanKhau(NhanKhauTableModel)
+ void initialize(URL,ResourceBundle)
+ void xacNhan(ActionEvent)
+ void cancle(ActionEvent)
}
class com.cnpm.controllers.TachHoKhauController {
+ Button moveToOld
+ Button moveToNew
+ TextField maHoKhauTim
- TableColumn<HoKhauTableModel,String> maHoKhauCol
- TableColumn<HoKhauTableModel,String> hoTenChuHoCol
- TableColumn<HoKhauTableModel,String> diaChiCol
- TableView<HoKhauTableModel> hoKhauTable
~ ObservableList<HoKhauTableModel> hoKhauView
- TableColumn<NhanKhauTableModel,String> maNhanKhauOldCol
- TableColumn<NhanKhauTableModel,String> hoTenNhanKhauOldCol
- TableColumn<NhanKhauTableModel,String> quanHeVoiChuHoOldCol
- TableView<NhanKhauTableModel> nhanKhauOldTable
~ ObservableList<NhanKhauTableModel> nhanKhauOldView
- TableColumn<NhanKhauTableModel,String> maNhanKhauNewCol
- TableColumn<NhanKhauTableModel,String> hoTenNhanKhauNewCol
- TableColumn<NhanKhauTableModel,String> quanHeVoiChuHoNewCol
- TableView<NhanKhauTableModel> nhanKhauNewTable
~ ObservableList<NhanKhauTableModel> nhanKhauNewView
- TextField maChuHoMoiTxt
- TextField maHoKhauMoiTxt
- TextField diaChiTxt
- TextField maKhuVucTxt
- TextField chuHoCuTxt
- TextField chuHoMoiTxt
- TextField maHoKhauTxt
- Button cancleBtn
- Label errorLab
- ChoiceBox<String> optionChoiceBox
~ Connection connection
- SharedDataModel sharedDataModel
~ Boolean maHoKhauhasExisted
~ String hoKhauSql
~ String nhanKhauSql
~ String submitSql
- ChoiceBox<String> choiceBox
- void refreshTable()
+ void initialize(URL,ResourceBundle)
+ void cancle(ActionEvent)
+ void submit(ActionEvent)
}
class com.cnpm.controllers.XoaQuaController {
- Button btn_cancel_them
- Button btn_confirm_them
- TextField note
- TextField dien_id_phat_qua
~ String query
~ Connection connection
~ ResultSet resultSet
~ PhatQua phatqua
~ PreparedStatement preparedStatement
+ void huy(ActionEvent)
+ void xacNhan(ActionEvent)
- void getQuery()
+ void initialize(URL,ResourceBundle)
}
class com.cnpm.controllers.ChuyenHoKhauController {
- TextField maHoKhauTxt
- TextField tenChuHoTxt
- TextField maKhuVucTxt
- TextField diaChiHienTaiTxt
- TextField diaChiChuyenDenTxt
- TextArea lyDoChuyenDiTxt
- Button submitBtn
- Button cancleBtn
- TableView<HoKhauTableModel> hoKhauTable
- TableColumn maHoKhauCol
- TableColumn hoTenChuHoCol
- TableColumn diaChiCol
- TextField maHoKhauTim
- ChoiceBox<String> optionChoiceBox
- Label errorLab
+ void initialize(URL,ResourceBundle)
+ void submit()
+ void cancle(ActionEvent)
}
class com.cnpm.controllers.TrangChuController {
- StackPane main_display
+ void hoKhau(ActionEvent)
+ void nhanKhau(ActionEvent)
+ void trangChu(ActionEvent)
+ void phatThuong(ActionEvent)
+ void phatQua(ActionEvent)
+ void minhChung(ActionEvent)
+ void thayDoi(ActionEvent)
+ void initialize(URL,ResourceBundle)
+ void changeDisplay(StackPane,String)
}


javafx.fxml.Initializable <|.. com.cnpm.controllers.ThemNhanKhauController
javafx.fxml.Initializable <|.. com.cnpm.controllers.PhatQuaController1
javafx.fxml.Initializable <|.. com.cnpm.controllers.XoaMinhChung
javafx.fxml.Initializable <|.. com.cnpm.controllers.ThemThuongController
javafx.fxml.Initializable <|.. com.cnpm.controllers.DangNhapController
javafx.fxml.Initializable <|.. com.cnpm.controllers.ThongKeNhanKhauController
javafx.fxml.Initializable <|.. com.cnpm.controllers.DangKyTamTruController
javafx.fxml.Initializable <|.. com.cnpm.controllers.HoKhauController
javafx.fxml.Initializable <|.. com.cnpm.controllers.NhanKhauController
javafx.fxml.Initializable <|.. com.cnpm.controllers.PhatThuongController1
javafx.fxml.Initializable <|.. com.cnpm.controllers.PhatThuongController
javafx.fxml.Initializable <|.. com.cnpm.controllers.ThayDoiNhanKhauController
javafx.fxml.Initializable <|.. com.cnpm.controllers.XoaThuongController
javafx.fxml.Initializable <|.. com.cnpm.controllers.ChonNhanKhauController
javafx.fxml.Initializable <|.. com.cnpm.controllers.MinhChungcontroller
javafx.fxml.Initializable <|.. com.cnpm.controllers.DoiChuHoController
javafx.fxml.Initializable <|.. com.cnpm.controllers.ThemQuaController
javafx.fxml.Initializable <|.. com.cnpm.controllers.MacDinhController
javafx.fxml.Initializable <|.. com.cnpm.controllers.PhatQuaController
javafx.fxml.Initializable <|.. com.cnpm.controllers.DangKyTamVangController
javafx.fxml.Initializable <|.. com.cnpm.controllers.XinCapGiayController
javafx.fxml.Initializable <|.. com.cnpm.controllers.LichSuThayDoiController
javafx.fxml.Initializable <|.. com.cnpm.controllers.ThemMinhChungController
javafx.fxml.Initializable <|.. com.cnpm.controllers.ThemHoKhauController
javafx.fxml.Initializable <|.. com.cnpm.controllers.TachHoKhauController
javafx.fxml.Initializable <|.. com.cnpm.controllers.XoaQuaController
javafx.fxml.Initializable <|.. com.cnpm.controllers.ChuyenHoKhauController
javafx.fxml.Initializable <|.. com.cnpm.controllers.TrangChuController
@enduml